### PR TITLE
added-login-error-message

### PR DESCRIPTION
**Pull request by SirSiegmeyer**

### CODE REVIEW

**Comment by SirSiegmeyer** [comment]
How can I prevent the page from always reloading? The message disapeares right away...

**Comment by fkropfhamer** [comment]
> How can I prevent the page from always reloading? The message disapeares right away...

fixed it 😎

**Comment by SirSiegmeyer** [comment]
Thx for fix!

**Comment by SirSiegmeyer** [comment]
Still have the same issue @fkropfhamer

**Pull request merged**
